const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function read(k){try{const v=JSON.parse(localStorage.getItem('bg-'+k)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[]}catch{return []}}
function write(k,v){try{localStorage.setItem('bg-'+k,JSON.stringify(v))}catch{toast('Браузер не разрешает сохранить выбор.')}sync()}
function toast(t){let e=document.createElement('div');e.className='toast';e.setAttribute('role','status');e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),3500)}
function sync(){let f=read('favorites'),c=read('compare');$$('[data-save]').forEach(b=>{let on=f.includes(b.dataset.save);b.setAttribute('aria-pressed',on);if(b.classList.contains('icon-btn'))b.textContent=on?'♥':'♡'});$$('[data-compare]').forEach(b=>{let on=c.includes(b.dataset.compare);b.setAttribute('aria-pressed',on);b.textContent=on?'✓ В сравнении':'+ Сравнить'});$$('[data-favorite-count]').forEach(e=>e.textContent=f.length);$$('[data-compare-count]').forEach(e=>e.textContent=c.length);$('.compare-tray').hidden=!c.length;let page=$('[data-saved-page]');if(page){let ids=page.dataset.savedPage==='compare'?c:f,n=0;$$('[data-saved-id]',page).forEach(e=>{e.hidden=!ids.includes(e.dataset.savedId);if(!e.hidden)n++});$('[data-empty]',page).hidden=!!n}}
$$('[data-save]').forEach(b=>b.addEventListener('click',()=>{let f=read('favorites'),id=b.dataset.save;write('favorites',f.includes(id)?f.filter(x=>x!==id):[...f,id])}));
$$('[data-compare]').forEach(b=>b.addEventListener('click',()=>{let f=read('compare'),id=b.dataset.compare;if(!f.includes(id)&&f.length>=3)return toast('Для сравнения выберите не больше трёх бань.');write('compare',f.includes(id)?f.filter(x=>x!==id):[...f,id])}));
$('[data-clear-compare]')?.addEventListener('click',()=>write('compare',[]));sync();
$('.menu-toggle')?.addEventListener('click',e=>{let on=$('.header nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',on);e.currentTarget.setAttribute('aria-label',on?'Закрыть меню':'Открыть меню')});
$$('.header nav a').forEach(a=>a.addEventListener('click',()=>{$('.header nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}));
function setHeroScene(button){let id=button.dataset.heroScene;$$('[data-hero-scene-image]').forEach(image=>image.hidden=image.dataset.heroSceneImage!==id);$$('[data-hero-scene]').forEach(item=>{let active=item===button;item.setAttribute('aria-selected',String(active));item.tabIndex=active?0:-1});$('[data-hero-scene-title]')?.replaceChildren(button.dataset.title);$('[data-hero-scene-description]')?.replaceChildren(button.dataset.description)}
$$('[data-hero-scene]').forEach((button,index,all)=>{button.addEventListener('click',()=>setHeroScene(button));button.addEventListener('keydown',event=>{let next=event.key==='ArrowDown'||event.key==='ArrowRight'?(index+1)%all.length:event.key==='ArrowUp'||event.key==='ArrowLeft'?(index+all.length-1)%all.length:event.key==='Home'?0:event.key==='End'?all.length-1:-1;if(next>=0){event.preventDefault();setHeroScene(all[next]);all[next].focus()}})});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$$('[data-zoom]').forEach(b=>b.addEventListener('click',()=>{let d=$('#lightbox');$('img',d).src=b.dataset.zoom;$('img',d).alt=b.dataset.caption;$('p',d).textContent=b.dataset.caption;d.showModal()}));
function tab(b){$$('[data-tab]').forEach(t=>{let on=t===b;t.setAttribute('aria-selected',on);t.tabIndex=on?0:-1;$('#panel-'+t.dataset.tab).hidden=!on;if(!on)$$('video',$('#panel-'+t.dataset.tab)).forEach(v=>v.pause())})}
$$('[data-tab]').forEach((b,i,all)=>{b.addEventListener('click',()=>tab(b));b.addEventListener('keydown',e=>{let j=e.key==='ArrowRight'?(i+1)%all.length:e.key==='ArrowLeft'?(i+all.length-1)%all.length:e.key==='Home'?0:e.key==='End'?all.length-1:-1;if(j>=0){e.preventDefault();tab(all[j]);all[j].focus()}})});

// The configuration draft is intentionally local-only until the approved CRM integration exists.
const configKey='bg-configuration-draft';
function configRead(){try{let v=JSON.parse(localStorage.getItem(configKey)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch{return {}}}
function configWrite(v){try{localStorage.setItem(configKey,JSON.stringify(v))}catch{toast('Браузер не разрешает сохранить выбор.')}}
function configRender(){let root=$('.configuration-page');if(!root)return;let state=configRead(),stoves=$$('[data-config-stove]',root),extras=$$('[data-config-extra]',root);let active=stoves.find(b=>b.dataset.configStove===state.stove)||stoves[0];if(!active)return;state.stove=active.dataset.configStove;state.stoveName=active.dataset.configName;state.extras=Array.isArray(state.extras)?state.extras:[];stoves.forEach(b=>b.setAttribute('aria-pressed',b===active));extras.forEach(b=>b.setAttribute('aria-pressed',state.extras.includes(b.dataset.configExtra)));let selected=extras.filter(b=>state.extras.includes(b.dataset.configExtra)).map(b=>$('b',b)?.textContent).filter(Boolean);let summary=$('[data-config-summary]',root),title=$('[data-config-summary-title]',root),lead=$('[data-lead]',$('.configuration-summary',root));title.textContent=state.stoveName;summary.textContent=selected.length?'Обсудить: '+selected.join(', ')+'.':'Выберите важные для вас решения — они появятся здесь.';if(lead)lead.dataset.intent='Хочу обсудить предварительную комплектацию бани. Печь: '+state.stoveName+(selected.length?'. Важно: '+selected.join(', ')+'.':'');configWrite(state)}
$$('[data-config-stove]').forEach(b=>b.addEventListener('click',()=>{let s=configRead();s.stove=b.dataset.configStove;s.stoveName=b.dataset.configName;configWrite(s);configRender()}));
$$('[data-config-extra]').forEach(b=>b.addEventListener('click',()=>{let s=configRead(),items=Array.isArray(s.extras)?s.extras:[],id=b.dataset.configExtra;s.extras=items.includes(id)?items.filter(x=>x!==id):[...items,id];configWrite(s);configRender()}));
$$('[data-config-reset]').forEach(b=>b.addEventListener('click',()=>{try{localStorage.removeItem(configKey)}catch{}configRender()}));
configRender();
